name: tic_tac_toe_assignment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^3.4.2
  stacked_services: ^1.3.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  stacked_generator: ^1.5.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tic_tac_toe.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
